//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT0720TênSV_61132767.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public string MaSV { get; set; }
        public string HoSV { get; set; }
        public string TenSV { get; set; }
        public System.DateTime Ngaysinh { get; set; }
        public bool Gioitinh { get; set; }
        public string AnhSV { get; set; }
        public string Diachi { get; set; }
        public string Malop { get; set; }
    
        public virtual LOP LOP { get; set; }
    }
}
